### ISSUE TITLE
Unable to connect to librenms DB

### ISSUE THREAD

**Issue by IlanRuiz** [CPNV-MON1/LibreNMS#1]
# How to recreate the issue

1. Connect to the server through SSH fallowing the standard connection to aws cli
2. Go to /opt/librenms folder
3. Exec the command `./validate.php`

# Issue description
The librenms database is unable to be contacted when we initiate the validate.php script

The database is accessible with the commande `mysql -u librenms -p`

**Comment by andre1400** [comment]
Ajout de l'utilisateur librenms dans le fichier /etc/sudoers
Accès à l'interface web : http://127.0.0.1:1080/
ajout des Credentials de mariadb pour lier la base de donnée
Création du nouvel utilisateur admin pour manager l'interface web
user : librenms
mdp : librenms
